Added LDAP test for Superset
stackabletech/integration-tests pull request #175
Opened 2022-03-10 10:15 UTC by sbernauer

## Description

## Review Checklist
- [ ] Code contains useful comments
- [ ] Changelog updated (or not applicable)

2022-03-11 15:35 UTC, siegfriedweber commented
The Superset integration tests do not run out of the box on my machine.

I created a test cluster with the following command:
```
./create_test_cluster.py --kind --operator superset=0.4.0-pr145
```

The first test run failed :

```
ldap-1.4.1/1-install-openldap | test step failed 1-install-openldap
```

Perhaps the timeouts must be increased.

The second test run failed:

```
retrieving API resource for secrets.stackable.tech/v1alpha1, Kind=SecretClass failed: the server could not find the requested resource
```

The `create_test_cluster.py` script was not adapted to install the `secret-operator` so I did this manually:

```
helm install secret-operator stackable-dev/secret-operator --version=0.3.0-nightly
```

The third test run failed:

```
    ldap-1.4.1/10-install-superset | test step failed 10-install-superset
    statefulsets.apps "superset-with-ldap-node-default" not found
```

The RBAC rules were not adapted:

```
2022-03-11T15:17:53.305704Z ERROR stackable_operator::logging::controller: Failed to reconcile object controller.name="supersetclusters.superset.stackable.tech" error=reconciler for object SupersetCluster.v1alpha1.superset.stackable.tech/superset-with-ldap.kuttl-test-cuddly-bluebird failed error.sources=[failed to retrieve authentication class myldap, Kubernetes reported error: ApiError: authenticationclasses.authentication.stackable.tech "myldap" is forbidden: User "system:serviceaccount:default:superset-operator-serviceaccount" cannot get resource "authenticationclasses" in API group "authentication.stackable.tech" at the cluster scope: Forbidden (ErrorResponse { status: "Failure", message: "authenticationclasses.authentication.stackable.tech \"myldap\" is forbidden: User \"system:serviceaccount:default:superset-operator-serviceaccount\" cannot get resource \"authenticationclasses\" in API group \"authentication.stackable.tech\" at the cluster scope", reason: "Forbidden", code: 403 }), ApiError: authenticationclasses.authentication.stackable.tech "myldap" is forbidden: User "system:serviceaccount:default:superset-operator-serviceaccount" cannot get resource "authenticationclasses" in API group "authentication.stackable.tech" at the cluster scope: Forbidden (ErrorResponse { status: "Failure", message: "authenticationclasses.authentication.stackable.tech \"myldap\" is forbidden: User \"system:serviceaccount:default:superset-operator-serviceaccount\" cannot get resource \"authenticationclasses\" in API group \"authentication.stackable.tech\" at the cluster scope", reason: "Forbidden", code: 403 }), authenticationclasses.authentication.stackable.tech "myldap" is forbidden: User "system:serviceaccount:default:superset-operator-serviceaccount" cannot get resource "authenticationclasses" in API group "authentication.stackable.tech" at the cluster scope: Forbidden]
```

So I removed the deployed `superset-operator` and started it outside of the cluster.

The next test run failed:

```
    ldap-1.4.1/11-login | running command: [sh -c kubectl exec -n $NAMESPACE python-0 -- python /tmp/login.py]
    ldap-1.4.1/11-login | 2022-03-11 15:28:12,216 DEBUG: Starting new HTTP connection (1): superset-with-ldap-node-default:8088
    ldap-1.4.1/11-login | 2022-03-11 15:28:12,221 DEBUG: http://superset-with-ldap-node-default:8088 "POST /api/v1/security/login HTTP/1.1" 401 29
    ldap-1.4.1/11-login | command terminated with exit code 1
```

I do not know what went wrong this time.

2022-03-14 11:40 UTC, sbernauer commented
Thanks for your feedack @siegfriedweber!
All problems should be resolved by now. Working with `./create_test_cluster.py --kind --operator superset=0.4.0-pr145`

2022-03-14 11:40 UTC, sbernauer commented
Thanks for your feedack @siegfriedweber!
All problems should be resolved by now. Working with `./create_test_cluster.py --kind --operator superset=0.4.0-pr145`

2022-05-03 13:37 UTC, siegfriedweber requested changes

2022-05-03 13:37 UTC, siegfriedweber commented on superset-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
> +    commons-operator: NIGHTLY # TODO put in t2
TODO is still open.

2022-05-03 13:37 UTC, siegfriedweber commented on superset-operator/tests/kuttl/ldap-1.4.1/02-install-test-container.yaml
> +  serviceName: python
Why is the service name necessary?

2022-05-03 13:37 UTC, siegfriedweber commented on superset-operator/tests/kuttl/ldap-1.4.1/20-install-superset-insecure-tls.yaml
> +        email: mail
Is there a reason why these field names are set in this Superset instance but not in the others?

2022-05-03 13:37 UTC, siegfriedweber commented on superset-operator/tests/kuttl/ldap-1.4.1/requirements.txt
> +urllib3==1.26.8
Is it intended that some of these versions are older than in the smoke tests?

2022-05-03 13:37 UTC, siegfriedweber commented on superset-operator/tests/kuttl/ldap-1.4.1/login.py
> +    for superset_insstance in superset_insstances:
Typos

```suggestion
    for superset_instance in superset_instances:
```

2022-05-06 07:43 UTC, sbernauer commented on superset-operator/tests/kuttl/ldap-1.4.1/02-install-test-container.yaml
> +  serviceName: python
Well that's the way StatefulSets work...
`kuttl` seems to accept non-valid StatefulSets, but if you try to `kubectl apply` this file the serviceName is needed for a valid sts.

2022-05-06 07:44 UTC, sbernauer commented on superset-operator/tests/kuttl/ldap-1.4.1/20-install-superset-insecure-tls.yaml
> +        email: mail
My intention was kind of "increasing the test coverage", so no real reason. Happy to remove them if you'd like

2022-05-09 13:10 UTC, siegfriedweber requested changes
I know that this pull request was not adapted to the latest changes in the operator and therefore was not ready to be reviewed. But I needed a working integration test to test the operator and wrote down all changes I made.

2022-05-11 09:13 UTC, sbernauer commented
Thanks for the hints!
Updated the tests, so that they work again

2022-05-11 09:14 UTC, sbernauer commented on superset-operator/tests/kuttl/ldap-1.4.1/requirements.txt
> +urllib3==1.26.8
Absolutely not ^^ I will look into it

2022-05-11 09:19 UTC, sbernauer commented on superset-operator/tests/kuttl/ldap-1.4.1/requirements.txt
> +urllib3==1.26.8
updated it

2022-05-13 08:16 UTC, adwk67 approved these changes
All tests now run successfully. As discussed with @sbernauer there a few things that will be addressed in https://github.com/stackabletech/superset-operator/issues/195.

2022-05-13 08:20 UTC, merged