Feature/kind cluster 2
stackabletech/integration-tests pull request #40
Opened 2021-12-02 17:12 UTC by razvan

## Description

Fixes #18 

## Review Checklist
- [ ] Code contains useful comments
- [ ] Changelog updated (or not applicable)

2021-12-02 17:44 UTC, maltesander reviewed
Im not through yet, just saw that druid, kafka and nifi have the same zookeeper.rs.
If we do not need to adapt it per product, i would put it into the global commons folder and reuse?

2021-12-02 17:44 UTC, maltesander commented on kafka-operator/tests/common/zookeeper.rs
> +}
This is identical to the druid one. Would it make sense to just put them in the global commons directory?

2021-12-03 08:41 UTC, razvan commented on kafka-operator/tests/common/zookeeper.rs
> +}
Yes this code is copy&paste and the main reason was to avoid the dependency hell. Putting this code in the commons crate has the disadvantage that:
- all tests depend on the zookeeper-crd even if they don't need it.
- all tests depend on the same version or the zk-crd

IMO a little code duplication is preferable here.

2021-12-03 11:21 UTC, maltesander requested changes
Just minor things.

2021-12-03 12:23 UTC, maltesander commented on kafka-operator/tests/common/zookeeper.rs
> +}
Ok im fine with leaving it as is then if it avoids the dependency salad :)

2021-12-03 13:17 UTC, razvan commented on commons/src/operator/setup.rs
> +        }
Done.

2021-12-03 13:17 UTC, razvan commented on commons/src/operator/setup.rs
> +    pub pods_terminated_delay: Option<Duration>,
Done.

2021-12-03 13:57 UTC, maltesander approved these changes
LGTM.

2021-12-03 14:36 UTC, siegfriedweber requested changes

2021-12-03 14:36 UTC, siegfriedweber commented on nifi-operator/tests/create_cluster.rs
> +use crate::common::zookeeper::build_zk_test_cluster;
```suggestion
use common::zookeeper::build_zk_test_cluster;
```

2021-12-03 14:36 UTC, siegfriedweber commented on nifi-operator/tests/monitoring.rs
> +use crate::common::zookeeper::build_zk_test_cluster;
```suggestion
use common::nifi::maximize_client_verification_time_out;
use common::zookeeper::build_zk_test_cluster;
```

2021-12-03 14:36 UTC, siegfriedweber commented on nifi-operator/tests/scale_cluster.rs
> +use crate::common::zookeeper::build_zk_test_cluster;
```suggestion
use common::nifi::maximize_client_verification_time_out;
use common::zookeeper::build_zk_test_cluster;
```

If you start with being nitpicking, you cannot stop in between. I wish I had not started. :D

2021-12-03 14:36 UTC, siegfriedweber commented on .gitignore
> +**/target
Is this necessary?

2021-12-03 14:40 UTC, razvan commented on .gitignore
> +**/target
Not right now. It would be if we had removed the .gitignore files in the sub-folders.

2021-12-03 15:08 UTC, razvan commented on README.md
> +This will set up a three node kind cluster called `integration-tests` and install the `superset-operator` along with a MiniIO cluster, the `trino-operator` and the `hive-operator`. When this is done,
Yes I was confused,

2021-12-03 15:08 UTC, razvan commented on create_test_cluster.sh
> +  kind create cluster --name ${KIND_CLUSTER_NAME} --config ${KIND_CLUSTER_CONFIG_FILE}
Done.

2021-12-03 15:14 UTC, razvan commented on create_test_cluster.sh
> +  install_operator ${OPERATOR_NAME} ${OPERATOR_VERSION}
The problem is there two types of dependencies:
- Those needed by the operator/product to run
- Those needed by the integration tests to run
The current implementation makes no distinction for simplicity's sake. Also you should test all operators :)

2021-12-03 15:30 UTC, siegfriedweber commented on create_test_cluster.sh
> +  install_operator ${OPERATOR_NAME} ${OPERATOR_VERSION}
That's okay for me.

2021-12-07 08:42 UTC, siegfriedweber commented
It could make sense to pin the versions of the dependent operators as mentioned in https://github.com/stackabletech/integration-tests/pull/44#pullrequestreview-824947948.

2021-12-07 08:47 UTC, siegfriedweber commented
`trino-operator/create_test_cluster.fish` is redundant and can be dropped.

2021-12-08 09:01 UTC, backstreetkiwi commented
Some of my PRs are waiting because I want to build on the changes of this PR. Any chance that it will be completed soon?

2021-12-09 09:28 UTC, siegfriedweber submitted a review, later dismissed
LGTM

2021-12-09 10:19 UTC, merged