CI: added Druid Operator Tests
stackabletech/integration-tests pull request #41
Opened 2021-12-02 21:39 UTC by backstreetkiwi

## Description
Execution of the Druid integration test in our CI.
The test has successfully run, see https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Druid%20Operator%20Integration%20Tests%20(flex)/1/

## Review Checklist
- [ ] Code contains useful comments
- [ ] Changelog updated (or not applicable)

2021-12-03 09:12 UTC, siegfriedweber requested changes

2021-12-03 09:12 UTC, siegfriedweber commented on druid-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +              metricsPort: 9505
The tests will create the necessary services as soon as #40 is merged. So the ZookeeperCluster definition can be removed.

2021-12-03 09:12 UTC, siegfriedweber commented on druid-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
> +              metricsPort: 9505
The tests will create the necessary services as soon as #40 is merged. So the ZookeeperCluster definition can be removed.

2021-12-03 09:12 UTC, siegfriedweber commented on druid-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +      numberOfNodes: 3
When the Druid integration tests are extended with ingestion jobs then one of the Kubernetes nodes needs the label `nodeType: druid-data`. The kind cluster setup script adds this label to one of the nodes so this should also be done on T2.

2021-12-03 18:02 UTC, backstreetkiwi commented on druid-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +              metricsPort: 9505
Okay, I wait for #40.

2021-12-03 18:02 UTC, backstreetkiwi commented on druid-operator/.ci/integration-tests/hcloud-centos-8/cluster.yaml
> +              metricsPort: 9505
OK.

2021-12-03 18:03 UTC, backstreetkiwi commented on druid-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +      numberOfNodes: 3
I'll have a look at that. I think I'll do it early in the test script using a `kubectl` command.

2021-12-09 16:12 UTC, backstreetkiwi commented on druid-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +              metricsPort: 9505
ZK service definition is removed, test still runs, see: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Druid%20Operator%20Integration%20Tests%20(flex)/4/

2021-12-09 16:13 UTC, backstreetkiwi commented on druid-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +      numberOfNodes: 3
Test script labels the nodes according to the kind cluster setup

2021-12-11 10:01 UTC, siegfriedweber approved these changes
LGTM

2021-12-12 19:37 UTC, merged