Feature/ci k8s
stackabletech/integration-tests pull request #42
Opened 2021-12-02 21:45 UTC by backstreetkiwi

## Description
Tests were migrated to dockerized operators, see successful test runs for review:
* Kafka: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Kafka%20Operator%20Integration%20Tests%20(flex)/13/
* NiFi: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/NiFi%20Operator%20Integration%20Tests%20(flex)/14/
* OPA: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/OPA%20Operator%20Integration%20Tests%20(flex)/13/
* Spark: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Spark%20Operator%20Integration%20Tests%20(flex)/13/
* ZooKeeper: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Zookeeper%20Operator%20Integration%20Tests%20(flex)/23/

## Review Checklist
- [ ] Code contains useful comments
- [ ] Changelog updated (or not applicable)

2021-12-03 10:50 UTC, siegfriedweber requested changes
* The test.sh files for monitoring-operator are not converted.
* The hive-operator tests have no .ci directory yet. They would require Python.
* The superset-operator tests have no .ci directory yet. They would require a PostgreSQL database.

2021-12-03 10:50 UTC, siegfriedweber commented on kafka-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +    zookeeper-operator: NIGHTLY
When #40 is merged then the ZookeeperCluster definition below is not needed anymore because the tests will create the required services on their own.

This comment applies to all other cluster.yaml files as well.

2021-12-03 10:50 UTC, siegfriedweber commented on kafka-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +    kafka-operator: "$KAFKA_OPERATOR_VERSION"
The kind cluster setup script also creates an opa-operator and a regorule-operator. These are not used in the tests at the moment but in my opinion T2 and the kind cluster should have the same setup.

This comment applies to the other cluster.yaml file for kafka-operator as well.

2021-12-03 10:50 UTC, siegfriedweber commented on kafka-operator/.ci/integration-tests/aws-centos-8/test.sh
> +./operator-logs.sh zookeeper > /target/zookeeper-operator.log
In case an opa-operator and a regorule-operator are added to the cluster then their log output should be stored as well.

This comment applies to all other test.sh files as well.

2021-12-03 10:50 UTC, siegfriedweber commented on opa-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +    opa-operator: "$OPA_OPERATOR_VERSION"
The kind cluster setup script also creates a regorule-operator. It is not used in the tests at the moment but in my opinion T2 and the kind cluster should have the same setup.

This comment applies to the other cluster.yaml file for opa-operator as well.

2021-12-03 17:42 UTC, backstreetkiwi commented
> * The test.sh files for monitoring-operator are not converted.
> 
> * The hive-operator tests have no .ci directory yet. They would require Python.
> 
> * The superset-operator tests have no .ci directory yet. They would require a PostgreSQL database.

* The Monitoring Operator is supposed to be removed, so I didn't change anything. I better delete them completely
* Hive and Superset are out of the scope of this PR. Here, I only migrate the tests that existed before.

2021-12-03 17:57 UTC, backstreetkiwi commented on kafka-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +    zookeeper-operator: NIGHTLY
Okay, I will wait for #40 and remove the ZK service from all cluster definitions

2021-12-03 17:59 UTC, backstreetkiwi commented on kafka-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +    kafka-operator: "$KAFKA_OPERATOR_VERSION"
The operators not listed here are installed as well, although not in a specific version. The default is "newest release" which is not possible until we get the released Helm charts. So if the newest released version is okay, I don't have to add them here.

2021-12-03 18:00 UTC, backstreetkiwi commented on kafka-operator/.ci/integration-tests/aws-centos-8/test.sh
> +./operator-logs.sh zookeeper > /target/zookeeper-operator.log
I will add them.

2021-12-03 18:01 UTC, backstreetkiwi commented on opa-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +    opa-operator: "$OPA_OPERATOR_VERSION"
see other comment regarding operator presence when no version is specified

2021-12-09 16:16 UTC, backstreetkiwi commented on opa-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +    opa-operator: "$OPA_OPERATOR_VERSION"
The regorule-operator is present, see in latest test run: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/OPA%20Operator%20Integration%20Tests%20(flex)/19/artifact/target/stackable-versions.txt/*view*/
The logs are also retrieved, see also in latest test run: https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/OPA%20Operator%20Integration%20Tests%20(flex)/19/artifact/target/regorule-operator.log/*view*/

2021-12-09 16:18 UTC, backstreetkiwi commented on kafka-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +    zookeeper-operator: NIGHTLY
ZK service definition is removed from all Kafka test cluster setups

2021-12-09 16:23 UTC, backstreetkiwi commented on kafka-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +    kafka-operator: "$KAFKA_OPERATOR_VERSION"
The 2 operators are now part of the cluster (because they were released), see https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/Kafka%20Operator%20Integration%20Tests%20(flex)/16/artifact/target/stackable-versions.txt/*view*/

2021-12-09 19:58 UTC, backstreetkiwi commented on kafka-operator/.ci/integration-tests/aws-centos-8/cluster.yaml
> +    zookeeper-operator: NIGHTLY
ZK service definition is also removed from all NiFi test cluster setups

2021-12-10 07:48 UTC, siegfriedweber approved these changes
LGTM

2021-12-12 13:55 UTC, merged